# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_area_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroarea',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='hero_area/img/'),
        ),
        migrations.AddField(
            model_name='heroarea',
            name='youtube_introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
