# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_area_plugin', '0002_auto_20180402_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroarea',
            name='image_file',
            field=models.ImageField(default='', upload_to='hero_area/img/'),
        ),
    ]
