# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_area_plugin', '0003_auto_20180402_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroarea',
            name='image_file',
            field=models.ImageField(blank=True, default='', null=True, upload_to='hero_area/img/'),
        ),
    ]
