# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me_plugin', '0002_auto_20180404_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcontact',
            name='working_location',
            field=models.CharField(blank=True, default='Ho Chi Minh, Vietnam', max_length=100, null=True),
        ),
    ]
