# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_models_header', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='description')),
                ('top_image', models.ImageField(blank=True, default='', max_length=500, null=True, upload_to='header/img/top_image/')),
                ('youtube_url', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_models.BaseModel')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='description')),
                ('avatar', models.ImageField(blank=True, default='', max_length=500, null=True, upload_to='profile/img/top_image/')),
                ('introduction_youtube_url', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            bases=('portfolio_models.basemodel',),
        ),
    ]
