# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-10 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_models.BaseModel')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('percentage', models.IntegerField(default=50)),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='skill/logo/')),
                ('class_name', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            bases=('portfolio_models.basemodel',),
        ),
    ]
