# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_models', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_models.BaseModel')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            bases=('portfolio_models.basemodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_models.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('message_text', models.TextField(blank=True, default='', null=True)),
            ],
            bases=('portfolio_models.basemodel',),
        ),
    ]
