# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='customer_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
