POSTGRES_USER=${POSTGRES_USER:-postgres}
POSTGRES_DB=${POSTGRES_DB:-postgres}
POSTGRES_HOST=${POSTGRES_HOST:-db}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
DB_BACKUP_CRON_SCHEDULE=${DB_BACKUP_CRON_SCHEDULE:-0 1 * * *}
CRON_ENV="POSTGRES_USER='$POSTGRES_USER'\nPOSTGRES_DB='$POSTGRES_DB'\nPOSTGRES_HOST='$POSTGRES_HOST'\nPOSTGRES_PORT='$POSTGRES_PORT'"
if [ -n "$POSTGRES_PASSWORD" ]; then
    CRON_ENV="$CRON_ENV\nPOSTGRES_PASSWORD='$POSTGRES_PASSWORD'"
fi
if [ ! -z "$DB_BACKUP_DELETE_OLDER_THAN" ]; then
    CRON_ENV="$CRON_ENV\nDELETE_OLDER_THAN='$DB_BACKUP_DELETE_OLDER_THAN'"
fi
echo -e "$CRON_ENV\n$DB_BACKUP_CRON_SCHEDULE /backup.sh 2>&1" | crontab -
crontab -l
exec "$@"