# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='profile_plugin_profile', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(max_length=250, upload_to='avatar/img/')),
                ('working_position', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('location', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('self_introduction', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='self_introduction')),
                ('programing_language', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('database', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('ide_and_tool', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('vcs_dvcs', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('framework', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='milestoneitem',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_plugin.Profile'),
        ),
    ]
