# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioAppConfig',
        ),
        migrations.RemoveField(
            model_name='project',
            name='app_config',
        ),
    ]
