# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20180403_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='top_image',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to='portfolio/img/top_image/'),
        ),
    ]
