# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20180403_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='top_image',
            field=models.ImageField(default='', max_length=500, upload_to='portfolio/img/top_image/'),
        ),
    ]
