# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_auto_20180403_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
