# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_embed_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Image')], default=1),
        ),
    ]
