# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_auto_20180404_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_homepage_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_list_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
