# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('portfolio_app', '0012_auto_20180628_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestWorkSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_app_latestworksection', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
