# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-04 04:31
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('portfolio_app', '0013_latestworksection'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_case',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='use_case', to='cms.Placeholder'),
        ),
    ]
