# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='about_me_plugin_skillcontainer', serialize=False, to='cms.CMSPlugin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SkillContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='about_me_plugin_skillcontent', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=100)),
                ('skill_percentage', models.IntegerField(default=50)),
                ('skill_type', models.PositiveSmallIntegerField(choices=[(1, 'ASP.NET'), (2, 'Angular'), (3, 'Nodejs'), (4, 'Vuejs')], default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
