# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('about_me_plugin', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='about_me_plugin_aboutme', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=250)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
