# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('about_me_plugin', '0003_auto_20180620_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='about_me_plugin_statistic', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100)),
                ('statistic', models.IntegerField()),
                ('statistic_unit', models.PositiveSmallIntegerField(choices=[(1, 'Integer'), (2, 'Percentage')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='skillcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
