# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_plugin', '0004_auto_20180620_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='font_icon',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
